### ISSUE TITLE
Auto updated to v3.9.9.14 and only runs lolminer

### ISSUE THREAD

**Issue by misterbrucewayne** [Minerx117/NemosMiner#74] opened 2021-01-13 02:21 UTC
The miner auto updated to 3.9.9.14 today and it's only running lolminer at horrible profitability. I tried to reset benchmarks/profitability but it still only tests lolminer on 3 nicehash algos. I'm going to go back to v3.9.9.13 or or v3.8 and turn off auto update, but just wanted to flag the issue and see if there was anything to fix this. Let me know if I can provide more info.

**Comment by UselessGuru** [comment] 2021-01-13 06:37
Thank you for your feedback.
> The miner auto updated to 3.9.9.14 today and it's only running lolminer at horrible profitability

What is the value for 'MinerSet' in your configuration file?
If it is 'null' then the config file was somehow not updated correctly. In this case go to 'edit configuration', select the desired value for 'Run [.....]' and save the config.

Can you see  a line 'Updated configuration file [...] to version [...]' in the log just after the auto update?

Otherwise please post the contents of (anonymized) config file.

There is no need to reset any stat data when updating.

**Comment by misterbrucewayne** [comment] 2021-01-13 15:33
> What is the value for 'MinerSet' in your configuration file?

Looks like I don't even have it in the 3.9.9.14 config file, so it is 'null'

> Can you see a line 'Updated configuration file [...] to version [...]' in the log just after the auto update?

Yup, I see: 'Updated configuration file 'C:\NemosMiner-testing\Config\config.json' to version 3.9.9.14.' as close to the last step in the autoupdate log.

Here's the config file anonymized. I put `<deleted>` so you know what I removed

`{
  "Algorithm": "",
  "AllowedBadShareRatio": 0.1,
  "APILogfile": "",
  "APIPort": 3999,
  "ApplyUnprofitableAlgorithmList": true,
  "AutoStart": true,
  "AutoUpdate": true,
  "BalancesTrackerLog": false,
  "BalancesTrackerPollInterval": 5,
  "CalculatePowerCost": true,
  "ConfigFileVersion": "3.9.9.14",
  "CPUMinerProcessPriority": -2,
  "Currency": [
    "USD",
    "mBTC"
  ],
  "Delay": 1,
  "DisableDualAlgoMining": false,
  "DisableMinerFee": false,
  "DisableMinersWithFee": false,
  "DisableSingleAlgoMining": false,
  "Donate": 5,
  "EstimateCorrection": false,
  "ExcludeDeviceName": [],
  "GPUMinerProcessPriority": -1,
  "IdlePowerUsageW": 60,
  "IdleSec": 120,
  "IgnoreMinerFee": false,
  "IgnorePoolFee": false,
  "IgnorePowerCost": false,
  "IncludeLegacyMiners": true,
  "IncludeOptionalMiners": true,
  "IncludeRegularMiners": true,
  "Interval": 240,
  "LogToFile": [
    "Info",
    "Warn",
    "Error",
    "Verbose",
    "Debug"
  ],
  "LogToScreen": [
    "Info",
    "Warn",
    "Error",
    "Verbose",
    "Debug"
  ],
  "MarginOfError": 0,
  "MinAccuracy": 0.5,
  "MinDataSamples": 20,
  "MinDataSamplesAlgoMultiplier": {
    "X25r": 3
  },
  "MinerInstancePerDeviceModel": true,
  "MinerName": [],
  "MineWhenIdle": false,
  "MinWorker": 10,
  "MonitoringServer": "https://nemosminer.com",
  "MonitoringUser": "",
  "MPHAPIKey": "<deleted>",
  "MPHUserName": "<deleted>",
  "NiceHashAPIKey": "<deleted>",
  "NiceHashAPISecret": "<deleted>",
  "NiceHashOrganizationId": "<deleted>",
  "NiceHashWallet": "<deleted>",
  "NiceHashWalletIsInternal": true,
  "OpenFirewallPorts": true,
  "PayoutCurrency": "BTC",
  "PoolName": [
    "Blockmasters",
    "MPH",
    "NiceHash",
    "ZergPool",
    "ZPool"
  ],
  "PoolTimeout": 30,
  "PowerPricekWh": {
    "00:00": 0.12,
    "12:00": 0.12
  },
  "PricePenaltyFactor": 1,
  "ProfitabilityThreshold": -99,
  "ProHashingAPIKey": "",
  "ProHashingUserName": "nemos",
  "Proxy": "",
  "Region": "US",
  "ReportToServer": false,
  "RunningMinerGainPct": 12,
  "ShowAccuracy": true,
  "ShowAllMiners": false,
  "ShowEarning": true,
  "ShowEarningBias": true,
  "ShowMinerFee": true,
  "ShowMinerWindows": "normal",
  "ShowMinerWindowsNormalWhenBenchmarking": true,
  "ShowPoolBalances": true,
  "ShowPoolFee": true,
  "ShowPowerCost": true,
  "ShowPowerUsage": true,
  "ShowProfit": true,
  "ShowProfitBias": true,
  "ShowWorkerStatus": false,
  "SnakeTailConfig": ".\\Utils\\NemosMiner_LogReader.xml",
  "SnakeTailExe": ".\\Utils\\SnakeTail.exe",
  "SSL": false,
  "StartGUIMinimized": true,
  "StartPaused": false,
  "SyncWindow": 3,
  "Transcript": false,
  "UIStyle": "Light",
  "UnrealPoolPriceFactor": 2,
  "Wallet": "<deleted>",
  "WarmupTime": 30,
  "Watchdog": true,
  "WatchdogCount": 3,
  "WebGUI": true,
  "WorkerName": "nemosrig1"
}
`

**Comment by misterbrucewayne** [comment] 2021-01-13 16:01
I just manually added `"MinerSet": 1,` to the Config file and it's running all the miners now

**Comment by UselessGuru** [comment] 2021-01-13 16:09
Maybe you got caught in between version update - there was an eraly version of 3.9.9.14 that did not update the config.

You could - just for a test - edit the config to a lower version ("ConfigFileVersion": "3.9.9.14") -> ("ConfigFileVersion": "3.9.9.13") , and remove 'MinerSet'. 
Then restart Nemos Miner. It should update the config and set MinerSet again.

**Comment by misterbrucewayne** [comment] 2021-01-13 16:59
I tried doing the auto update again from my 3.9.9.13 backup this morning, but that didn't work (still no MinerSet and only runs lolminer). I also tried downloading a fresh [3.9.9.14](https://github.com/Minerx117/NemosMiner/tree/v3.9.9.14), but looks like that's still v3.8xx. 

However I tried what you suggested by just editing the ConfigFileVersion from 3.9.9.14 to 3.9.9.13 and removing MinerSet, and that worked! MinerSet was added back in as 'null' and then when I went to the Web UI config and saved it, it updated to MinerSet = 1.

**Comment by UselessGuru** [comment] 2021-01-13 19:00
>  MinerSet was added back in as 'null'

That's exactly what should NOT happen. :-(
It should get set to '1' when updating the config. I'll have a look and fix it. Thanks for reporting.

Edit: Root cause found. Will be fixed in the next version

**Comment by misterbrucewayne** [comment] 2021-01-13 20:00
Got it. Thanks for looking into it! A couple other issues - lmk if you prefer separate issues to track or if hijacking this one is fine:

I've had several miners where the bad shares are pretty significant and it keeps running. I confirmed `"AllowBadShareRatio": 0.1,` is in the config file and the running config. Does this typically check when both benchmarking and running normal? I'll keep an eye out for a couple examples and share the logs.

Also on the last couple versions, the CcminerLyraYesscrypt-v8.21r18v5 miner on Zergpool/Lyra2z330 reports an absurd profitability of like $90,000+ USD. I've benchmarked several times to see if it adjusts but it always is really high and I just disable the miner. It's reporting a Hash of 554.95MH/s and Power of 61W - running two Nvidia GTX 1080s. It's easy to just disable the miner, but wanted to flag.

**Comment by UselessGuru** [comment] 2021-01-13 20:45
> Does this typically check when both benchmarking and running normal?

Both. It will kick the miner it the bad share rate is above the threshold.
What miners/pools are affected? Are you overclocking (too much)?

> CcminerLyraYesscrypt-v8.21r18v5

I'll have a look. I get 2.4MH/s on my 1660 super.
I have seen miners report absurd values, but thats when OCd too much and the driver crashined while mining.
What's the miner reporting on the screen when this happens?

Edit:
> Hash of 554.95MH/s and Power of 61W

61W is way too low. The GPU is not working.

**Comment by misterbrucewayne** [comment] 2021-01-13 22:00
> Both. It will kick the miner it the bad share rate is above the threshold.
What miners/pools are affected? Are you overclocking (too much)?

I actually only started messing with overclocking in the last day or two, but prior I was just set to Power 75% and base memory/core. I haven't spent a ton of time lately, but I'm sitting at 75% power, -50 core, +400 memory for both GTX 1080s right now. I need to find something easy to benchmark with so I can mess around with the values and test it after each change - any suggestions?

>What's the miner reporting on the screen when this happens?

I'll run it a bit later and report back

>61W is way too low. The GPU is not working.

Yup that was my thinking, especially since I set Base power at 60W. It's the only miner reporting anything sub-100W. I'll take a look at it again, because I think Afterburner is showing heavy activity but I could be remembering wrong.


Got another random one for you. Is the miner profitability shown for both/all GPUs running, or is the profitability for one of the GPUs and if you were running two GPUs it would be 2x what is shown? I thought it was the former (total profitability for both GPUs running), but for a few days my profitability in the Legacy Miner GUI was counting the GPU Proft x 2. So for example if it showed PhoenixMiner had profit of $3 in the miner list, the Legacy Miner GUI was showing $6 while PhoenixMiner was running since I have 2 GPUs. Now it's back to showing it 1x, which I assume is correct. Can you confirm?

Really appreciate all of you support. I'm very much a beginner on all of this, but enjoy messing around with it even if I'm not cranking much of a profit and your tool is awesome.

**Comment by UselessGuru** [comment] 2021-01-13 22:07
>  I need to find something easy to benchmark with so I can mess around with the values and test it after each change - any suggestions?

Not really. It seem virtually imposssible to find a GENERAL best OC combo. Some algos prefer lov CPU speed & hig mem clock (e.g. Ethash), other algos scream for the highes GPU clock. 
Make sure you use EthPill.

> Legacy Miner GUI was counting the GPU Proft x 2

Can you provide a screen shot - I am not sure that I understand your point.

**Comment by misterbrucewayne** [comment] 2021-01-13 22:50
> Make sure you use EthPill.

I'll check it out - thanks!

>Can you provide a screen shot - I am not sure that I understand your point.

Yeah let me try to explain it with current screenshots - here's what it's showing right now:
![Screenshot 2021-01-13 153149](https://user-images.githubusercontent.com/35897270/104518397-d7ec6480-55b4-11eb-9bbd-8de9eb46bdd4.png)
![Screenshot 2021-01-13 153256](https://user-images.githubusercontent.com/35897270/104518404-d884fb00-55b4-11eb-8aa3-78c6ae44df30.png)

In the first image, PhoenixMiner/Ethash (2x GPUs) is running at $3.0522 earnings and SRBMminerMulti/CryptonightUpx (CPU) is running at $0.3802 earnings (ignoring the bias column). That makes total earnings $3.43 ($3.0522 + $0.3802), which is displayed in the Legacy Miner GUI in the second screenshot.

Now what it was doing a couple days ago on v3.9.9.13 (using the same numbers above as an example) was showing my earnings as $6.48 ($3.0522 **+ $3.0522** (2x GPUs) + $0.3802). Essentially it was taking the displayed GPU earnings x 2 + CPU earnings. It was doing the same with power costs as well. 

Here's a screenshot I happened to take a couple of days ago with different numbers showing the significantly higher earnings (and power usage). 
![image](https://user-images.githubusercontent.com/35897270/104519590-ea679d80-55b6-11eb-8a89-881f34599627.png)

I'm just trying to figure out is it calculating correct now (first screenshots) or if it should be taking the displayed earnings x 2 when running on 2 GPUs like it was a couple of days ago? My thinking is that it's correct now and was just overstating it a couple of days ago when it was doubling the GPU earnings displayed for the miner.

Hope that helps explain...

**Comment by misterbrucewayne** [comment] 2021-01-13 23:01
For Ethpill, recommend either of these? Looks like the main one went offline. Thinking the first one given it was updated more recent? Sorry, noob when it comes to this stuff.

https://github.com/tbates76/Ethpill
https://github.com/admin-ipfs/OhGodAnETHlargementPill

**Comment by UselessGuru** [comment] 2021-01-13 23:04
Thank you.

The data from 3.9.9.13 seems wrong. 3.9.9.14 is OK.

You can find the same information in 3 places:
- Legacy GUI
- Text window
- Web GUI / Dashboard

They are all fed by the same variable ($Variables.Summary).
http://localhost:3999/functions/variables/get?Summary

The values represent the total sum of all devices. If you have 2x GTX 1080, then you'll have ONE GPU (Devices GPU#00 & GPU#01) miner running creating an amount X. Then you have the CPU miner running generating an amount Y. So the total earning should be X+Y.

**Comment by UselessGuru** [comment] 2021-01-13 23:08
> For Ethpill, recommend either of these? 

The binary should be the same. So it does not matter.
Just keep the pill window running at all times. Note: You will need to re-benchmark to get accurate (higher) results.

**Comment by misterbrucewayne** [comment] 2021-01-13 23:27
> The values represent the total sum of all devices. If you have 2x GTX 1080, then you'll have ONE miner running creating an amount X. Then you have the CPU miner running generating an amount Y. So the total earning should be X+Y.

Got it - thanks. While disappointed it's the lower number, that is what I was expecting.

>The binary should be the same. So it does not matter.
Just keep the pill window running at all times. Note: You will need to re-benchmark to get accurate (higher) results.

Thank you! Appreciate all your time!

**Comment by misterbrucewayne** [comment] 2021-01-14 16:24
It's actually doing the whole GPU x2 in the profit/power calculation again

![Screenshot 2021-01-14 092353](https://user-images.githubusercontent.com/35897270/104618722-50e9cb80-564a-11eb-9917-e9d8c2aa5fda.png)
![Screenshot 2021-01-14 092211](https://user-images.githubusercontent.com/35897270/104618723-51826200-564a-11eb-8ceb-cf7aee60960a.png)

**Comment by misterbrucewayne** [comment] 2021-01-14 18:25
> It's actually doing the whole GPU x2 in the profit/power calculation again
> 
> ![Screenshot 2021-01-14 092353](https://user-images.githubusercontent.com/35897270/104618722-50e9cb80-564a-11eb-9917-e9d8c2aa5fda.png)
> ![Screenshot 2021-01-14 092211](https://user-images.githubusercontent.com/35897270/104618723-51826200-564a-11eb-8ceb-cf7aee60960a.png)

I was messing with EthPill and OC settings before another benchmarking process so maybe that has something to do with it. I am re-benchmarking now and will see if it still doubles up

**Comment by UselessGuru** [comment] 2021-01-14 19:53
> so maybe that has something to do with it.

I doubt it.
I rather suspect an issue with having two cards of the same model (2x 1080). This will be a hard one to troubleshoot 'cause I only have 1x 1660.
Does it happen right from  the start, or after a specific event?

I had a look at the code and I saw something that is not OK. ~~Can you replace NemosMiner.ps1 with the one in the attached zip file?
[NemosMiner.zip](https://github.com/Minerx117/NemosMiner/files/5816703/NemosMiner.zip)~~

**Comment by misterbrucewayne** [comment] 2021-01-14 19:56
Yeah not the end of the world and easy to figure out actual profitability when it does.

>Does it happen right from the start, or after a specific event?

I believe it's from the start, but I will keep an eye on it next time and confirm. I have a lot of benchmarking still to do.

>I had a look at the code and I saw something that is not OK. Can you replace NemosMiner.ps1 with the one in the attached zip file?

Yup will copy it in. Anything that would require restarting benchmarks?

Edit: 
I saw it also auto updated to v.15 today. If that ps1 file was in that update then I may already have it

**Comment by UselessGuru** [comment] 2021-01-14 19:58
> If that ps1 file was in that update then I may already have it

No, I just made it especially for you - but it will be in the next release.

**Comment by misterbrucewayne** [comment] 2021-01-14 19:59
❤️

**Comment by misterbrucewayne** [comment] 2021-01-14 20:01
>NemosMiner.zip

Looks like this isn't the ps1 file, but the bat file to start the miner. Maybe that's the same thing or it will update ps1?

**Comment by UselessGuru** [comment] 2021-01-14 20:07
The poblem lies here:

https://github.com/Minerx117/NemosMiner/commit/1b32b99d469058a778eab2d9cba0a68c6ff7db7c

Forget the zip file. Just udated 3.9.9.15 in the repo. Hope this fixes it.
You need to re-download and copy the files (actually only \Includes.core.ps1)

**Comment by misterbrucewayne** [comment] 2021-01-14 20:17
Cool will do it now. Any reason to restart benchmarking with this change?

**Comment by UselessGuru** [comment] 2021-01-14 20:22
> Cool will do it now. Any reason to restart benchmarking with this change?

No.

**Comment by misterbrucewayne** [comment] 2021-01-15 01:39
It finished benchmarking, but now it's not showing Profit in the Browser or Legacy GUI, even though it has it on the individual miners in the text window and on the Dashboard

![Screenshot 2021-01-14 183822](https://user-images.githubusercontent.com/35897270/104669666-c334cd00-5697-11eb-8193-b1bde2b905a3.png)

**Comment by UselessGuru** [comment] 2021-01-15 05:54
> but now it's not showing Profit in the Browser or Legacy GUI,

Try \Includes\code.ps1 form the attached Zip file. I tried another fix. 
[NemosMiner-testing.zip](https://github.com/Minerx117/NemosMiner/files/5818716/NemosMiner-testing.zip)

Thank you for your patience. As said I can only guess cause I
 cannot reproduce myself.

**Comment by misterbrucewayne** [comment] 2021-01-16 17:13
It's actually showing profitability again, but it's still showing 2x GPU. Not a big deal as I can just cut it in half to know where I'm at, but I'm also happy to keep testing if you want - up to you.

^ this is true with 3.9.9.16 that updated early this morning too

**Comment by UselessGuru** [comment] 2021-01-16 22:45
@misterbrucewayne

Could you please post the outputs of:

http://localhost:3999/functions/variables/get?SortedMiners
http://localhost:3999/functions/variables/get?FastestMiners
http://localhost:3999/functions/variables/get?BestMiners
http://localhost:3999/functions/variables/get?Miners_Device_Combos
http://localhost:3999/functions/variables/get?BestMiners_Combo

Put each output in its own file (replace confidential information with ***************). Zip it all up and upload it here. Thank you.

**Comment by misterbrucewayne** [comment] 2021-01-18 16:41
@UselessGuru here you go - let me know if you need anything else. I _think_ I got all the confidential information out of there...

~outputs - nemosminer.zip~

**Comment by UselessGuru** [comment] 2021-01-18 17:35
@misterbrucewayne 

Thank you - so far the files did not show what I was hoping for.
Did you have the double-earnings problem when you did the export?

What are your currency settings & power price?
Would you mind exporting 'http://localhost:3999/functions/variables/get?miners' when the problem happens?
Remove the confidential information (Wallets / MinigPoolHub) data.

If you want you can contact me (uselessGuru) on discord.

**Comment by misterbrucewayne** [comment] 2021-01-18 17:45
I had the miner active, but I stopped it to pull these (still left all the windows open, just idle state). Assuming that's not an issue? But to your question, the double counting was happening before I stopped it and after I started it again between pulling the. I'm not at my computer but will pull that file shortly

**Comment by misterbrucewayne** [comment] 2021-01-18 17:46
Currency is USD,mBTC and payout is BTC. Power price is a flat $0.12, set as "00:00=0.12" or something like that to capture all times. I can verify that though

**Comment by UselessGuru** [comment] 2021-01-18 18:06
>  Assuming that's not an issue? 

Jep, it is. It is best to export the data while it is collecting hashrate data.
I think I have to think about a magic 'debug' button that will export debug data. :-)

**Comment by misterbrucewayne** [comment] 2021-01-18 18:09
Got it. I'll repull in addition to the other one you asked for

**Comment by misterbrucewayne** [comment] 2021-01-19 16:01
@UselessGuru - here's a new output file while the miner is running and the GPU double counting is happening, plus added a file for '/get?miners' 

[outputs - nemosminer v2.zip](https://github.com/Minerx117/NemosMiner/files/5837068/outputs.-.nemosminer.v2.zip)

**Comment by misterbrucewayne** [comment] 2021-01-19 16:09
>If you want you can contact me (uselessGuru) on discord.

Went to add you, but need the 4 digit tag on your username. Mine is misterbrucewayne#0972 if you want to chat through there. Either way works for me.

Edit:
>Power price is a flat $0.12, set as "00:00=0.12" or something like that to capture all times. I can verify that though

also, confirmed my power is set to the 0.12, but like this '{"00:00":0.12,"12:00":0.12}'

**Closed as completed** 2021-01-22 05:57 UTC
