### ISSUE TITLE
Feature Request - Take Power Consumption Per Algo into Account

### ISSUE THREAD

**Issue by Minerx117** [Minerx117/NemosMiner#5] opened 2019-06-20 06:34 UTC
https://github.com/nemosminer/NemosMiner/issues/399

**Comment by Minerx117** [comment] 2019-07-01 09:49
https://github.com/nemosminer/NemosMiner/issues/399

**Comment by UselessGuru** [comment] 2020-05-13 13:46
Work in progress here:

https://github.com/Minerx117/NemosMiner/tree/testing

**Comment by UselessGuru** [comment] 2020-07-22 07:39
Please test and report any findings here.

Known issues:
- MiniZ 1.6v4 is currently using the binary from 1.6v3 (cannot update binary repo)

**Comment by szentigrad3** [comment] 2020-08-02 05:23
it isn't picking up my card even though i have set it up like u said in the pdf
https://i.imgur.com/Mo7w0iA.png
https://i.imgur.com/4AeRb5c.png

**Comment by UselessGuru** [comment] 2020-08-16 19:30
@szentigrad3 

Pls apologize for the late response - I was not expecting anyone actually using this build :-)

There is an error in the documentation.
Here is the correct one:
https://github.com/Minerx117/NemosMiner/commit/cec665daa2db9a87d48214578d1fe0cbfaf2afd8

**Comment by szentigrad3** [comment] 2020-08-17 10:28
i just tried it with the new documentation and same error > https://i.imgur.com/wd5phBa.png

**Comment by UselessGuru** [comment] 2020-08-17 13:48
You are also using CPU mining, so you must also configure CPU#00

**Comment by szentigrad3** [comment] 2020-08-17 13:59
got it working

**Comment by szentigrad3** [comment] 2020-08-17 14:06
https://i.imgur.com/ExG8EJH.png

**Comment by UselessGuru** [comment] 2020-08-17 14:32
Cool!
I'll soon update to a new version (lots of fixes)

**Comment by szentigrad3** [comment] 2020-08-17 15:46
got 3 failed miners out of the whole lot

https://i.imgur.com/0np33ni.png
https://i.imgur.com/NlpKIi4.png
https://i.imgur.com/6JSbgHY.png

also this all update to show LTC when its set
https://i.imgur.com/iIDyCcZ.png

Also feels like the profits are wrong

**Comment by UselessGuru** [comment] 2020-08-17 19:24
> got 3 failed miners out of the whole lot

https://i.imgur.com/0np33ni.png
-> Try excluding Yesscrypt algorithm by adding '-Yesscrypt' to your config.

https://i.imgur.com/NlpKIi4.png
-> What was the exact command line executed in this case (to be found in the switching log)? 
I cannot reproduce the issue. Does adding --intensity [some number] help?

https://i.imgur.com/6JSbgHY.png
-> I cannot see any error message

> also this all update to show LTC when its set

I don't understand. What should I see in the screen shot?

> Also feels like the profits are wrong

Please be more specific. What seems not OK?

**Comment by szentigrad3** [comment] 2020-08-18 13:50
> https://i.imgur.com/NlpKIi4.png
> -> What was the exact command line executed in this case (to be found in the switching log)?
> I cannot reproduce the issue. Does adding --intensity [some number] help?

Bin\CcminerLyraYesscrypt-v8.21r18v5\ccminer.exe --algo lyra2z330 --timeout 1 --url stratum+tcp://103.249.70.7:4563 --user MUEUQ5Aq84hn6Gjs3vFzT1kSYJfJi3f4ez --pass ID=jj,c=LTC,mc=GXX --cpu-priority 4 --timeout 50000 --retry-pause 1 --api-bind 4001 --devices 0", haven't tried intensity yet

> https://i.imgur.com/6JSbgHY.png
> -> I cannot see any error message

it was not receiving any data so it failed

> > also this all update to show LTC when its set
> 
> I don't understand. What should I see in the screen shot?
 
the pools uptop think i am mining BTC not LTC, so its calculating for BTC not LTC

> > Also feels like the profits are wrong
> 
> Please be more specific. What seems not OK?

just compared to other miners i have used, usually top is Equihash*** algos

**Comment by UselessGuru** [comment] 2020-08-22 16:21
@szentigrad3 

I've uploaded the latest code. Happy testing.

> the pools uptop think i am mining BTC not LTC, so its calculating for BTC not LTC

By default NemosMiner is using BTC for all pools & calculations.

Nemos miner does support LTC, but you'll have to create/edit .\config\PoolsConf.json and set 'PayoutCurrency' & 'Wallet' for the pools you want to be paid in LTC

**Comment by szentigrad3** [comment] 2020-08-22 16:56
everytime i save my details and run the .bat again this happens > https://i.imgur.com/7ajICrb.png

**Comment by szentigrad3** [comment] 2020-08-22 17:21
i fixed it somehow i kept trying

**Comment by UselessGuru** [comment] 2020-08-22 20:51
Your config file is corrupt - use https://jsonblob.com/ (or a similar service) to inspect the json structure.

**Comment by szentigrad3** [comment] 2020-08-23 03:02
only just got a chance to try it and this keeps coming up now > https://i.imgur.com/8Wwbqsy.png

**Comment by UselessGuru** [comment] 2020-08-23 08:12
@szentigrad3 

Please post your config files (config.json & poolsconfig.json, both to be found in the config folder.

When posing remember to hide sensitive information in the files.

**Comment by szentigrad3** [comment] 2020-08-23 08:42
[Config.zip](https://github.com/Minerx117/NemosMiner/files/5113728/Config.zip)

**Comment by UselessGuru** [comment] 2020-08-24 05:13
@szentigrad3 

Thank you for your information.

I can reproduce your issuses.

1. No pools. This is caused by an error in the script related to donation ~~- will be fixed soon.
As a workaround you can try disabling donation 'Donation=0'~~
Fixed in https://github.com/Minerx117/NemosMiner/commit/9f18f81086df08806bc19eed38d1db213cb92936

2. LTC
Nemos Miner is designed for BTC. Individual pools can be configured to use LTC ect.
This however will currently break the earnings summary calculations.

-> In Config.json:
- Set Wallet to a BTC address
- Set PasswordCurrency to 'BTC'

->In PoolsConfi.json for each relevant pool
- Set Wallet to a LTC address
- Set PasswordCurrency to 'LTC'

3. mLTC 
This is currently not supported at all.

I'll see how I can change the code to cover all your needs, Stay tuned.

**Comment by szentigrad3** [comment] 2020-08-24 08:49
https://i.imgur.com/Xgmy01y.png
https://i.imgur.com/eKy60Fh.png
https://i.imgur.com/TSNlB5N.png < all the same for all algos

**Comment by UselessGuru** [comment] 2020-08-24 11:17
@szentigrad3 

> https://i.imgur.com/Xgmy01y.png

For such issues please post the command line executed

> https://i.imgur.com/eKy60Fh.png

Know problem with BMiner. Please check with the miner vendor for a solution (www.bminer.me)
There is nothing wrong with NemosMiner per se. NM just builds command lines to execute miners.

> https://i.imgur.com/TSNlB5N.png

Something is blocking the TCP port
I've seen this before, but only when a miner locked the TCP port during a previous miner crash
What happens if you:
1. Copy the commend line
2. Restart your computer
3. Execute the command line
???

BTW: I recommend you to use SnakeTail (See the bottom of the readme file)

**Comment by szentigrad3** [comment] 2020-08-24 11:33
> @szentigrad3
> 
> > https://i.imgur.com/Xgmy01y.png
> 
> For such issues please post the command line executed

"2020-08-24T18:45:11","GPU#00","CcminerDyn-v1.0.2-1xRTX2080Ti11GB {Argon2dDyn@ZergPoolCoins}","MUEUQ5Aq84hn6Gjs3vFzT1kSYJfJi3f4ez","NaN","NaN","Bin\CcminerDyn-v1.0.2\ccminer.exe --algo argon2d --statsavg 1 --url stratum+tcp://103.249.70.7:4239 --user MUEUQ5Aq84hn6Gjs3vFzT1kSYJfJi3f4ez --pass jj,c=LTC,mc=DYN --cpu-priority 4 --retry-pause 1 --api-bind 4001 --devices 0"


>BTW: I recommend you to use SnakeTail (See the bottom of the readme file)

i see nothing about it

**Comment by UselessGuru** [comment] 2020-08-24 11:43
@szentigrad3 

I meant changelog.txt :-)

- Support for external log viewer (Download Snaketail from https://github.com/snakefoot/snaketail-net/releases and put in '\Utils' folder)

**Comment by szentigrad3** [comment] 2020-08-24 11:48
> > https://i.imgur.com/TSNlB5N.png
> 
> Something is blocking the TCP port
> I've seen this before, but only when a miner locked the TCP port during a previous miner crash
> What happens if you:
> 
> 1. Copy the commend line
> 2. Restart your computer
> 3. Execute the command line
>    ???

no change, same thing happens

BTW: i also DMed you on discord

**Comment by UselessGuru** [comment] 2020-08-24 11:50
![image](https://user-images.githubusercontent.com/30080938/91041702-c2c86680-e610-11ea-849e-04c201223e84.png)

I cannot reproduce this issue. It might be a pool issue.

**Comment by UselessGuru** [comment] 2020-08-24 11:51
> BTW: i also DMed you on discord

I cannot see anthing

**Comment by szentigrad3** [comment] 2020-08-24 11:57
> > BTW: i also DMed you on discord
> 
> I cannot see anthing

DM me szentigrade#1079

**Comment by szentigrad3** [comment] 2020-08-24 12:21
@UselessGuru 
also ethminer gets no data so i get a 0 hashrate > https://imgur.com/6JSbgHY

> Know problem with BMiner. Please check with the miner vendor for a solution ([www.bminer.me](http://www.bminer.me))
> There is nothing wrong with NemosMiner per se. NM just builds command lines to execute miners.

can't find any answers on there at all, google search doesn't help oh well

**Closed as completed** 2020-10-02 16:03 UTC
Labels: enhancement, help wanted, ready for testing
