### ISSUE TITLE
Configuration not saving? & hashrate not being shown

### ISSUE THREAD

**Issue by grantemsley** [Minerx117/NemosMiner#83] opened 2022-06-08 00:07 UTC
Fresh install of the latest release. From the web interface, edit configuration, clicking "appply configuration" just resets the entire form back to defaults.

I can manually edit the config.json file and make changes, but don't seem to be able to change anything from the webui and have it stick.

Am I just doing it wrong?

**Comment by UselessGuru** [comment] 2022-06-08 09:16
Hi Grant

Cool to see you here :-)

I cannot reproduce your issue. It could be a localisation issue.
What happens when you delete your existing config (\Config\Config.json). Can you then edtt the config with the config editor?
Can you spot the error when you open the web debugger in your browser (F12)?
Could it be that you only have one device (invalid array handling)?

Would you mind posting the non-saveable config file?

**Comment by grantemsley** [comment] 2022-06-08 13:19
And cool to see you're still maintaining this. Good work!

Did another test, just extracted NemosMiner-4.0.0.39.zip to a new folder and ran nemosminer.bat. Getting the same results, the webui opens but I can't change anything. I just tried making a single, simple change like changing the miningpoolhub user name, or BTC address. Once I hit apply it goes back to what it was before.

F12 console shows a couple errors:

    jQuery.Deferred exception: Cannot set properties of null (setting 'checked') TypeError: Cannot set properties of null (setting 'checked')
    Uncaught TypeError: Cannot set properties of null (setting 'checked')

Clicking those errors points at this line of code:

    document.getElementById(('region-' + config.Region).toLowerCase()).checked = "true";

I tried making sure a region is selected, but that won't save either.

At this point there is no Config.json, the config folder is empty. If I click Edit Config file, it opens notepad which prompts me to create the file. I created the empty file and closed notepad. Still couldn't save any changes.  Closed nemosminer completely and reopened it, and this time it generated a config.json with stuff in it and now saving changes works somehow. But my original install still doesn't work even after restarting it.

Tried copying the config.json from the broken install to this new and somehow working this time install, and it broke, so definitely an error in the config file.

Ah! I figured it out! The broken config had:  "Region": "Europe West". There is a warning in the logs that locations have changed and to check your config. I have no idea how it created the config file with that old value selected by default. But having an unelectable region seems to break config saving.

**Comment by UselessGuru** [comment] 2022-06-08 13:24
> Ah! I figured it out! The broken config had: "Region": "Europe West". There is a warning in the logs that locations have changed and to check your config. I have no idea how it created the config file with that old value selected by default. But having an unelectable region seems to break config saving.

That error is already fixed in https://github.com/Minerx117/NemosMiner/commit/5d5b7e0c79f101ad40c63cd0b0d95ecd431408db
edit: additional fix: https://github.com/Minerx117/NemosMiner/commit/062cb9995bb3c629276630161a7a7b94aadf8597

> jQuery.Deferred exception

Nothing we can do - but it does not seem to hurt either ;-)

> And cool to see you're still maintaining this. Good work!

I am doing all the work. Nemo seems to have abandoned it :-(

For a chat head over to discord (UselessGuru#2032). Or do you still use skype?

**Comment by grantemsley** [comment] 2022-06-08 15:23
Awesome. Added you on discord.

**Comment by Minerx117** [comment] 2022-06-14 21:38
Fresh install of the latest release. From the web interface, edit configuration, clicking "appply configuration" just resets the entire form back to defaults. Previous Release's seem to applying/saving config ok.

eg. i can download .38 autoupdate to .39(latest) save and apply config everything works. but if i download .39(latest) this happens: https://youtu.be/UsdSu1Yqw1s

**Comment by Minerx117** [comment] 2022-06-15 00:54
also found that hash rate is being  calculated and stored in the stat file correctly but is not being shown in the gui 
here is example of downloading .38 and updating to latest .39 and config works correctly 

eg: https://youtu.be/6dpC9EYsVDQ

**Comment by UselessGuru** [comment] 2022-06-15 13:19
> eg. i can download .38 autoupdate to .39(latest) save and apply config everything works.

Fixed with https://github.com/Minerx117/NemosMiner/commit/5d5b7e0c79f101ad40c63cd0b0d95ecd431408db (Will be in 4.0.1.0)

**Comment by UselessGuru** [comment] 2022-06-15 13:40
Fixed in https://github.com/Minerx117/NemosMiner/releases/tag/v4.0.1.0

**Closed as completed** 2022-06-15 23:58 UTC
